name: Build and Release Executables

on:
  push:
    tags:
      - 'v*' # Trigger on new tags starting with v (e.g., v1.0.0)
  workflow_dispatch: # Allow manual trigger

jobs:
  # --- 1. BUILD WINDOWS EXECUTABLE ---
  build_windows_exe:
    runs-on: windows-latest
    
    env:
      PYINSTALLER_ALWAYS_CMD: "True"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install Pillow vtf2img numpy openexr-numpy pyinstaller
          
      - name: Run PyInstaller to create EXE
        # References your script name: SkyboxConverter.py
        run: pyinstaller --onefile --name skybox_stitcher SkyboxConverter.py

      - name: Upload Windows Executable Artifact
        # The artifact name must be consistent for the download step
        uses: actions/upload-artifact@v4
        with:
          name: skybox_stitcher_windows_exe
          path: dist/skybox_stitcher.exe
          retention-days: 7
          
  # --- 2. BUILD LINUX EXECUTABLE ---
  build_linux_executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install System Dependencies for OpenEXR
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenexr-dev

      - name: Install Python Dependencies
        run: pip install Pillow vtf2img numpy openexr-numpy pyinstaller

      - name: Run PyInstaller
        # References your script name: SkyboxConverter.py
        run: pyinstaller --onefile --name skybox_stitcher SkyboxConverter.py

      - name: Upload Linux Executable Artifact
        # The artifact name must be consistent for the download step
        uses: actions/upload-artifact@v4
        with:
          name: skybox_stitcher_linux_executable
          path: dist/skybox_stitcher
          retention-days: 7

  # --- 3. CREATE GITHUB RELEASE AND ATTACH ARTIFACTS ---
  create_release:
    # Only runs if the previous build jobs succeeded
    needs: [build_windows_exe, build_linux_executable]
    # Only runs if the push was triggered by a tag (e.g., v1.0.0)
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          # Targets all files in the downloaded artifact folders (./artifacts)
          files: artifacts/**
          # Uses the tag name (e.g., v1.0.0) as the name of the release
          name: Release ${{ github.ref_name }}
          # Ensures the release is not marked as a pre-release. 
          # The most recent non-prerelease will automatically be marked as "Latest".
          prerelease: false
          body: |
            ## Skybox Stitcher Release ${{ github.ref_name }}
            
            This release includes the Windows and Linux executables for the latest version.
