name: Build and Release SkyboxConverter

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5 # Using v5 for latest compatibility
        with:
          python-version: '3.10' # Set a specific version for reliability

      - name: Install dependencies
        # Install all known required libraries explicitly
        run: |
          python -m pip install --upgrade pip
          pip install Pillow vtf2img numpy openexr-numpy pyinstaller

      - name: Build SkyboxConverter.py (One-File)
        # Assuming your script is named 'SkyboxConverter.py' (with capital C)
        run: pyinstaller SkyboxConverter.py --onefile --hidden-import vtf2img --collect-all openexr_numpy --name SkyboxConverter --icon=icon.ico

      - name: Upload artifact (Single EXE)
        uses: actions/upload-artifact@v4
        with:
          name: SkyboxConverter-exe
          path: dist/SkyboxConverter.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    # Only run the release job if the build job succeeded.
    if: success()

    steps:
      - uses: actions/checkout@v4
        # Need to fetch history to create and push the new tag
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SkyboxConverter-exe
          path: ./artifacts

      # --- CRITICAL FIX: Create and push the 'latest' tag ---
      - name: Set and Push 'latest' Tag
        run: |
          # Delete existing local and remote 'latest' tag
          git tag -d latest || true
          git push origin :latest || true
          # Create and push the new 'latest' tag
          git tag latest
          git push origin latest

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/SkyboxConverter.exe
          # Use the 'latest' tag we just created
          tag_name: latest
          name: SkyboxConverter - Latest Build
          draft: false
          prerelease: false
          # Ensure your GITHUB_TOKEN has 'contents: write' permission
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}