name: Build Single Executable

on:
  push:
    tags:
      - 'v*' # Trigger on new tags starting with v (e.g., v1.0.0)
  workflow_dispatch: # Allow manual trigger

jobs:
  build_windows_exe:
    # Use Windows to generate the .exe file
    runs-on: windows-latest
    
    # Set a custom environment variable often required for PyInstaller to work with complex packages
    env:
      PYINSTALLER_ALWAYS_CMD: "True"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python Dependencies
        # Install all required libraries, including PyInstaller
        run: pip install Pillow vtf2img numpy openexr-numpy pyinstaller
          
      - name: Run PyInstaller to create EXE
        # IMPORTANT: References your script name
        run: pyinstaller --onefile --name skybox_stitcher SkyboxConverter.py

      - name: Upload Executable Artifact
        # Uploads the finished .exe file from the 'dist' folder
        uses: actions/upload-artifact@v4
        with:
          name: skybox_stitcher_windows_exe
          path: dist/skybox_stitcher.exe
          retention-days: 7
          
  build_linux_executable:
    # Use Linux to generate an executable for other platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install System Dependencies for OpenEXR
        # Required for openexr-numpy to install correctly on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenexr-dev

      - name: Install Python Dependencies
        run: pip install Pillow vtf2img numpy openexr-numpy pyinstaller

      - name: Run PyInstaller
        # IMPORTANT: References your script name
        run: pyinstaller --onefile --name skybox_stitcher SkyboxConverter.py

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skybox_stitcher_linux_executable
          # The PyInstaller output file on Linux is named just 'skybox_stitcher'
          path: dist/skybox_stitcher
          retention-days: 7